### PR TITLE
Add workflow for automatically building and pushing Docker Images.

### PR DESCRIPTION
**Pull request by N0tACyb0rg**
I'll look into seeing if I can have it automatically create tags, but this just rebuilds it and pushes it to Docker Hub when a commit is made.
**IMPORTANT**
You do need to add the DOCKERHUB_USERNAME and DOCKERHUB_TOKEN secrets on this screen in the repository settings page:
image
For the DOCKERHUB_TOKEN you need to create a PAT (like for GitHub) on your Docker Hub account. There's a guide [here](https://docs.docker.com/docker-hub/access-tokens/) if you need it.

### CODE REVIEW

**Comment by HLSiira** [comment]
Is this a commit to the main branch? I'd rather it not rebuild for commits to development

**Comment by N0tACyb0rg** [comment]
Just set it to only trigger on main.

**Comment by HLSiira** [comment]
Build is failing, claims it can't find the docker file

```
buildx failed with: ERROR: failed to solve: failed to read dockerfile: open /tmp/buildkit-mount1552714894/Dockerfile: no such file or directory
```

**Comment by N0tACyb0rg** [comment]
Yeah I saw, I'm trying to figure out why.

**Pull request merged**
