### PR TITLE
PHP8 basic fixes

### LINKED ISSUE #292: Can't complete setup on nginx with php-fpm
Hey all, 

bit of a weird one - have a host with Nginx and PHP8.3 (FPM) and i can't get past the Initial Setup page. 

i've checked my php-fpm and nginx with some custom php scripts, i can create files and directories from php, so it's unlikely a file permission problem (i think). 

when filling out and then pressing the install button i get the following in the address bar 

"http://IP/a/?username=matt&password=xxx&validate=xxx&projectName=dev&projectPath=dev&domain=&development=true&analytics=true&timezone=Pacific%2FMidway"

and the page returns to a blank initial setup state. no DIR's are created in the workspace dir, and the config.php file contains no infomation/is blank. 

Where should i go next to trouble shoot this?

### PR DESCRIPTION
**Pull request by SimLV**
Basic PHP8 fixes (extensive testing required)

Ability to start in container for testing purposes 

This should fix #292

### CODE REVIEW

**Comment by HLSiira** [comment]
Hey, there actually is a [Docker Repo](https://github.com/Atheos/Atheos-Docker) already for Atheos; I don't really see the value in merging it into here, but I'm open to discussion on it. I like them as separate because I view them as separate "products" if that makes sense, and it keeps the commit history separate.

The PHP8 fixes are interesting; just out of curiosity, what kind of bugs are you seeing?

**Comment by SimLV** [comment]
This is "testing docker" with PHP 8. So it has `develop` mode ON for php so there are warnings in output. 
These warnings destroyed some expected jsons

- `deprecated null` for debug_backtrace
- `unsupported null` for str_replace
- these cause client side JS crash on file menu

Thinking of Docker image. This is just oneliner command to test empty fresh installation without anything. It could be removed but now it is useful.

**Comment by HLSiira** [comment]
Makes sense but if that's the case then I'd rather this be a push to the docker repo then, if it's geared at testing PHP8 on docker.

**Comment by SimLV** [comment]
Removed docker part from here

**Pull request merged**
